apiVersion: v1
kind: PersistentVolume
metadata:
 name: "pg-pv-volume"
spec:
 capacity:
   storage: 3Gi
 accessModes:
   - ReadWriteMany
 persistentVolumeReclaimPolicy: Recycle
 awsElasticBlockStore:
   volumeID: vol-0a310d2dd7a7ed6b4
   fsType: ext4